#!/bin/bash

xsource=""
target_code=""
target_err=""
lcc="./lcc"

while [[ $# -gt 0 ]]; do
    if [[ $1 == -o ]]; then
        shift
        target_code=$1
    elif [[ $1 == -e ]]; then
        shift
        target_err=$1
    else
        xsource=$1;
    fi
    shift
done

if [[ $xsource == "" ]]; then
    printf "No source code found!\n"
else
    cat $xsource | $lcc 1>$target_code 2>$target_err
    printf "Finished!\n"
fi
exit
